plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = '21.0.12'

    modules = ['javafx.controls', 'javafx.fxml']
}


sourceSets.main.output.resourcesDir = sourceSets.main.java.destinationDirectory.get().asFile

application {
    mainModule = 'studentregistration'

    mainClass.set(providers.gradleProperty('app').orElse('studentregistration.Main'))
}
